### ISSUE TITLE
Update this library for Jackson 2.6.x

### ISSUE THREAD

**Issue by apatrida** [joschi/jackson-datatype-threetenbp#4]
Update and test this library for Jackson 2.6.x and issue a matching release.

**Comment by joschi** [comment]
Are there any incompatibilities with Jackson 2.6.0 or 2.6.1 right now? Otherwise it should just work™.

**Comment by joschi** [comment]
Fixed in 5d5a64286563e7b37c7d3b2900baf930f109e051.
