### ISSUE TITLE
Android Three Ten Backport

### ISSUE THREAD

**Issue by thegarlynch** [joschi/jackson-datatype-threetenbp#59]
for : https://github.com/JakeWharton/ThreeTenABP

**Comment by joschi** [comment]
@thegarlynch Could you please elaborate on the differences of [ThreeTen Backport](https://www.threeten.org/threetenbp/) and https://github.com/JakeWharton/ThreeTenABP?

**Comment by thegarlynch** [comment]
Basically more efficient implementation of ThreeTenBP on android

**Comment by joschi** [comment]
As far as I understand, you can use this project as-is with ThreeTenABP since it's based on ThreeTenBP.

The only difference is how the timezone data is handled which has nothing to do with this project.

**Comment by thegarlynch** [comment]
yeah.. i've already fork it so it can show threetenabp. can i have your permission to publish it to maven or something ?. what license information that i should include ?

**Comment by joschi** [comment]
This project is licensed under the Apache 2.0 License (https://github.com/joschi/jackson-datatype-threetenbp/blob/master/LICENSE.txt), so feel free to fork it.

It's unnecessary, though, since it works fine with https://github.com/JakeWharton/ThreeTenABP. 🤷

**Comment by thegarlynch** [comment]
hmm... i could just exclude jsr-310.. ah, i just solved my problem own problem in complicated way

**Comment by joschi** [comment]
@thegarlynch Thanks for your input.

Since you've resolved the problem you had, I'll close this issue. 😃
