### ISSUE TITLE
Jackson 2.8

### ISSUE THREAD

**Issue by cbornet** [joschi/jackson-datatype-threetenbp#8]
Is it possible to upgrade this project to the latest jackson version ?

**Comment by joschi** [comment]
@cbornet If there's demand for it, I might update the library to Jackson 2.8.

Is there anything not working with it right now? Have you tried simply using Jackson 2.8 with this library?

**Comment by cbornet** [comment]
I'm mostly interested by the commits done on jackson-datatype-jsr310 for https://github.com/FasterXML/jackson-datatype-jsr310/issues/79

**Comment by joschi** [comment]
@cbornet I've synced this project with the official [jackson-datatype-jsr310](https://github.com/FasterXML/jackson-datatype-jsr310) 2.8.4 and the release should hit Maven Central soon.

**Comment by cbornet** [comment]
:+1:

**Comment by thegarlynch** [comment]
this should already be closed right ?

**Comment by joschi** [comment]
@thegarlynch Yes, this issue has been closed almost 4 years ago and culminated in jackson-datatype-threetenbp 2.8.4 😉

**Comment by thegarlynch** [comment]
hey.. can i fork your repository to implement ThreeTen A BP by JakeWharton for android ? could you tell me what i miss about the license.
