### ISSUE TITLE
Update to latest Jackson

### ISSUE THREAD

**Issue by samgurtman** [joschi/jackson-datatype-threetenbp#9]
Hi @joschi,

Thanks for making this great library! Is there any way this can be updated to the latest Jackson version? I could possibly do it and open a PR if you give me some guidance on how you've done it in the past.

**Comment by joschi** [comment]
@samgurtman Any particular reason you've closed this issue?

**Comment by samgurtman** [comment]
I realised the latest Jersey is tracking 2.8.4 still. I'll reopen as it may
still be useful to others.
